create table tradeable_asset (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ticker text,
  name text,
  primary_exchange text,
  market_cap integer,
  address jsonb,
  sic_descriptor text,
  total_employees integer
);