create table industry_report (
  id bigint generated by default as identity primary key,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ticker_id integer,
  analyst text,
  report_year smallint,
  report_path text,
  measured_year smallint,
  revenue integer,
  gross_income bigint,
  ebitda bigint,
  income_tax integer,
  constraint fk_ticker
  foreign key (ticker_id) references tradeable_asset(id)
);